//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.ORDERR = new HashSet<ORDERR>();
        }
    
        public int cliID { get; set; }
        public string cliName { get; set; }
        public string cliAddress { get; set; }
        public string cliCountry { get; set; }
        public string cliPostOfficeCode { get; set; }
        public string cliPhone { get; set; }
        public Nullable<int> cliStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERR> ORDERR { get; set; }
    }
}
