//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMATION_ORDER
    {
        public int infoOrderID { get; set; }
        public Nullable<int> ordID { get; set; }
        public Nullable<int> prodID { get; set; }
        public Nullable<int> infoOrderSL { get; set; }
        public Nullable<decimal> infoOrderPrice { get; set; }
        public Nullable<int> infoStatus { get; set; }
    
        public virtual ORDERR ORDERR { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
