//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERR()
        {
            this.INFORMATION_ORDER = new HashSet<INFORMATION_ORDER>();
        }
    
        public int ordID { get; set; }
        public Nullable<System.DateTime> ordDate { get; set; }
        public string ordDescription { get; set; }
        public Nullable<bool> ordBill { get; set; }
        public Nullable<int> cliID { get; set; }
        public Nullable<int> staID { get; set; }
        public Nullable<int> ordStatus { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMATION_ORDER> INFORMATION_ORDER { get; set; }
        public virtual STAFF_LOGIN STAFF_LOGIN { get; set; }
    }
}
