//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.INFORMATION_ORDER = new HashSet<INFORMATION_ORDER>();
        }
    
        public int prodID { get; set; }
        public string prodName { get; set; }
        public Nullable<decimal> prodPrice { get; set; }
        public Nullable<int> prodSL { get; set; }
        public string prodInit { get; set; }
        public string prodCamera { get; set; }
        public Nullable<int> prodMenory { get; set; }
        public Nullable<int> prodReleaseYear { get; set; }
        public Nullable<int> prodRAM { get; set; }
        public string prodDescription { get; set; }
        public Nullable<int> provID { get; set; }
        public Nullable<int> catID { get; set; }
        public Nullable<int> prodStatus { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual COLOR COLOR { get; set; }
        public virtual IMAGES IMAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMATION_ORDER> INFORMATION_ORDER { get; set; }
        public virtual PROVIDED PROVIDED { get; set; }
    }
}
