//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVIDED()
        {
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public int provID { get; set; }
        public string provFullName { get; set; }
        public string provName { get; set; }
        public string provAddress { get; set; }
        public string provPostOfficeCode { get; set; }
        public string provCountry { get; set; }
        public string provPhone { get; set; }
        public string provDescription { get; set; }
        public Nullable<int> provStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}
