//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public int staID { get; set; }
        public string staName { get; set; }
        public Nullable<System.DateTime> staBirthday { get; set; }
        public string staAddress { get; set; }
        public byte[] staImg { get; set; }
        public string staPhone { get; set; }
        public Nullable<bool> staSex { get; set; }
        public string staDescription { get; set; }
        public Nullable<decimal> staSalary { get; set; }
        public string staPosition { get; set; }
        public Nullable<int> LoginID { get; set; }
        public Nullable<int> staStatus { get; set; }
    
        public virtual STAFF_LOGIN STAFF_LOGIN { get; set; }
    }
}
